[package]
name = "volume-viewer"
version = "0.1.0"
authors = ["Lukas Herzberger <herzberger.lukas@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = ["crates/*"]

[features]
default = [
    "console_error_panic_hook"
]

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[dependencies]
bevy_utils = "0.7.0"
instant = "0.1.12"
log = "0.4.17"
reqwest = "0.11.10"
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }
wasm-logger = "0.2.0"
web-sys = { version = "0.3.57", features = ["Document", "HtmlCanvasElement"] }

ome-ngff = { path = "crates/ome-ngff", features = ["log"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
