name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --cfg=web_sys_unstable_apis

    steps:
    - uses: actions/checkout@v3
    - name: Install Clippy
      run: rustup component add clippy
    - name: Lint
      run: cargo clippy --all-targets --all-features -p volume-viewer -- --no-deps -D warnings
    #- name: Build
    #  run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
